### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ModyQyW** [ModyQyW/uni-helper#20]
### Clear and concise description of the problem 对问题的清晰和简明的描述

目前，uni-helper 还有很多可提高的地方。如果你感兴趣，不妨领任务加入开发。谢谢。

#### 项目支持

- [ ] 一个单独的 eslint 配置包以校验 `androidPrivacy.json`
- [ ] 一个单独的 eslint 配置包以校验 `pages.json`
- [ ] 一个单独的 eslint 配置包以校验 `manifest.json`
- [ ] 在 [@modyqyw/fabric](https://github.com/ModyQyW/fabric) 里集成以上配置

#### 插件支持

- [x] VSCode
  - [x] `androidPrivacy.json`
  - [x] `pages.json`
  - [x] `manifest.json`
- [x] OpenVSX
  - [x] `androidPrivacy.json`
  - [x] `pages.json`
  - [x] `manifest.json`
- [ ] WebStorm
  - [ ] `androidPrivacy.json`
  - [ ] `pages.json`
  - [ ] `manifest.json`
- [ ] Sublime Text
  - [ ] `androidPrivacy.json`
  - [ ] `pages.json`
  - [ ] `manifest.json`

#### 项目支持

无

#### 插件支持

- [x] VSCode
- [x] OpenVSX
- [ ] WebStorm
- [ ] Sublime Text

#### 项目支持

无

#### 插件支持

- [x] VSCode
- [x] OpenVSX
- [ ] WebStorm
- [ ] Sublime Text

#### 项目支持

无

#### 插件支持

- [x] VSCode
- [x] OpenVSX
- [ ] WebStorm
- [ ] Sublime Text

#### 项目支持

无

#### 插件支持

- [x] VSCode
- [x] OpenVSX
- [ ] WebStorm
- [ ] Sublime Text

### @modyqyw/uni-request

- [ ] 在实际项目中测试
- [ ] 优化 TypeScript 类型
- [ ] 切换到 TypeScript

### uni-app-types

- [ ] 在实际项目中测试
- [ ] 优化类型

### uni-cloud-types

- [ ] 在实际项目中测试
- [ ] 优化类型

### uni-ui-types

- [ ] 在实际项目中测试
- [ ] 优化类型

### Validations 检查

- [X] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md) 遵循我们的 [行为准则](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate. 检查是否已经有一个要求相同功能的问题，以避免重复创建。
